import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RealtimePollProvider } from "../components/RealtimePollProvider";
import { gothamMedium, gothamUltra, goldplayBlack } from "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
    interactiveWidget: 'resizes-content'
  },
  other: {
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'apple-mobile-web-app-title': 'YouthHub',
    'application-name': 'YouthHub',
    'msapplication-TileColor': '#000000',
    'theme-color': '#000000'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Prevent pull-to-refresh on mobile devices
              document.addEventListener('DOMContentLoaded', function() {
                let startY = 0;
                let currentY = 0;
                
                document.addEventListener('touchstart', function(e) {
                  startY = e.touches[0].clientY;
                }, { passive: false });
                
                document.addEventListener('touchmove', function(e) {
                  currentY = e.touches[0].clientY;
                  
                  // Prevent pull-to-refresh when scrolling up at the top
                  if (window.scrollY === 0 && currentY > startY) {
                    e.preventDefault();
                  }
                  
                  // Prevent pull-to-refresh when scrolling down at the bottom
                  if (window.scrollY + window.innerHeight >= document.documentElement.scrollHeight && currentY < startY) {
                    e.preventDefault();
                  }
                }, { passive: false });
                
                // Prevent overscroll behavior
                document.body.style.overscrollBehavior = 'none';
                document.documentElement.style.overscrollBehavior = 'none';
                
                // Mobile browser UI hiding
                function hideMobileBrowserUI() {
                  // Set viewport height to prevent address bar from showing
                  const vh = window.innerHeight * 0.01;
                  document.documentElement.style.setProperty('--vh', \`\${vh}px\`);
                  
                  // Add mobile app classes
                  document.body.classList.add('mobile-full-height');
                  
                  // Prevent address bar from showing on scroll
                  let lastScrollTop = 0;
                  window.addEventListener('scroll', function() {
                    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
                    if (scrollTop > lastScrollTop) {
                      // Scrolling down - try to hide address bar
                      if (window.innerHeight < window.outerHeight) {
                        window.scrollTo(0, 1);
                      }
                    }
                    lastScrollTop = scrollTop;
                  });
                }
                
                // Hide mobile browser UI on load and resize
                if (window.innerWidth <= 768) {
                  hideMobileBrowserUI();
                  window.addEventListener('resize', hideMobileBrowserUI);
                  window.addEventListener('orientationchange', function() {
                    setTimeout(hideMobileBrowserUI, 100);
                  });
                }
                
                // iOS specific: prevent address bar from showing
                if (/iPad|iPhone|iPod/.test(navigator.userAgent)) {
                  // Prevent zoom on double tap
                  let lastTouchEnd = 0;
                  document.addEventListener('touchend', function(event) {
                    const now = (new Date()).getTime();
                    if (now - lastTouchEnd <= 300) {
                      event.preventDefault();
                    }
                    lastTouchEnd = now;
                  }, false);
                  
                  // Prevent address bar from showing
                  window.addEventListener('load', function() {
                    setTimeout(function() {
                      window.scrollTo(0, 1);
                    }, 0);
                  });
                }
              });
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gothamMedium.variable} ${gothamUltra.variable} ${goldplayBlack.variable} antialiased dark`}
      >
        <RealtimePollProvider>
          {children}
        </RealtimePollProvider>
      </body>
    </html>
  );
}
